<script setup lang="ts">
useHead({
  title: 'Privacy Policy · Listen Direct',
  meta: [{ name: 'description', content: 'How the Listen Direct demonstration handles account, session, cookie, and voice data.' }],
})
</script>

<template>
  <main class="legal-page">
    <nav><NuxtLink class="legal-brand" to="/"><span><i /><i /><i /></span>LISTEN<strong>/DIRECT</strong></NuxtLink><div><NuxtLink to="/terms">Terms of Use</NuxtLink><NuxtLink to="/login">Sign in</NuxtLink></div></nav>
    <header><span>LEGAL / PRIVACY</span><h1>Privacy Policy</h1><p>Effective August 19, 2026 · Demo version 1.0</p></header>
    <div class="legal-layout">
      <aside><a href="#scope">Scope</a><a href="#data">Information</a><a href="#use">How we use it</a><a href="#audio">Voice data</a><a href="#cookies">Cookies</a><a href="#retention">Retention</a><a href="#rights">Your choices</a><a href="#security">Security</a><a href="#contact">Contact</a></aside>
      <article>
        <div class="legal-notice"><strong>Prototype notice</strong><p>This policy describes the current Listen Direct demonstration. It is a product document, not a substitute for review by qualified privacy counsel before a public production launch.</p></div>
        <section id="scope"><span>01</span><h2>Scope and operator</h2><p>Listen Direct is a demonstration of audio-native voice infrastructure. This policy covers the application, authentication system, dashboard, administration view, cookies, and any future voice-processing features operated under the Listen Direct name.</p><p>The entity deploying this software is responsible for identifying itself as the data controller or business, publishing valid contact details, and adapting this policy to its jurisdiction and actual vendors.</p></section>
        <section id="data"><span>02</span><h2>Information we process</h2><h3>Account information</h3><p>The demo includes fixture names, email addresses, roles, and workspace assignments. A production identity system may also process credentials, organization membership, authentication events, and account-support communications.</p><h3>Session and security information</h3><p>The application processes a sealed session identifier, login time, role, workspace, and security-related request information needed to authenticate users and protect restricted routes.</p><h3>Usage and technical information</h3><p>A deployed service may receive IP addresses, browser and device information, requested URLs, timestamps, error reports, and operational logs from its hosting and security providers. Optional analytics must remain disabled until consent is recorded where required.</p></section>
        <section id="use"><span>03</span><h2>How information is used</h2><ul><li>Authenticate users and enforce demo, user, and administrator permissions.</li><li>Provide voice-session operations, routing, evaluations, and privacy controls.</li><li>Secure, maintain, troubleshoot, and improve the service.</li><li>Measure product use only when optional analytics are enabled.</li><li>Comply with valid legal obligations and protect users, the service, and others.</li></ul></section>
        <section id="audio"><span>04</span><h2>Voice and acoustic data</h2><p><strong>The current dashboard does not capture microphone audio or send audio to an AI model.</strong> Its waveform, transcripts, sessions, and acoustic signals are simulated locally for product demonstration.</p><p>If live processing is added, the product must disclose the model providers, purposes, retention period, storage regions, transcript behavior, derived acoustic signals, consent requirements, and deletion controls before collection begins. Sensitive trait inference should be prohibited unless a documented lawful and ethical use case requires it.</p></section>
        <section id="cookies"><span>05</span><h2>Cookies and device storage</h2><div class="cookie-table"><div><b>Name</b><b>Purpose</b><b>Category</b><b>Duration</b></div><div><code>nuxt-session</code><p>Encrypted authentication and role session</p><span>Strictly necessary</span><small>2 hours for demo; 8 hours for users/admins</small></div><div><code>ld-cookie-preferences</code><p>Remembers essential-only or analytics choice</p><span>Strictly necessary</span><small>180 days</small></div></div><p>No analytics provider is currently connected. If analytics are introduced, they must not load until the user opts in where consent is required. Cookie settings can be reopened at any time from the lower-left corner of the application.</p></section>
        <section id="retention"><span>06</span><h2>Retention and disclosure</h2><p>Authentication cookies expire automatically. Demo dashboard records exist in browser memory and disappear when the page is refreshed. Production retention periods must be defined from the actual database, hosting, logging, model, backup, and legal requirements.</p><p>Personal information should be shared only with documented service providers, professional advisers, or authorities when legally required. It should not be sold or used for cross-context behavioral advertising without a separate, explicit policy and appropriate choices.</p></section>
        <section id="rights"><span>07</span><h2>Your choices and rights</h2><p>Users can decline optional analytics, reopen cookie settings, sign out, and ask the deploying operator about access, correction, deletion, restriction, portability, or objection rights that apply in their jurisdiction. Withdrawing optional consent must be as easy as granting it.</p></section>
        <section id="security"><span>08</span><h2>Security</h2><p>The demo uses scrypt password verification, constant-time comparison, sealed HTTP-only cookies, same-site cookie restrictions, expiring sessions, route guards, and server-side role checks. No security control eliminates all risk. Production deployment also requires secret management, TLS, rate limiting, monitoring, backups, incident response, and regular testing.</p></section>
        <section id="contact"><span>09</span><h2>Changes and contact</h2><p>Material changes should be announced through the product and reflected in the effective date. Before production, the deploying entity must provide its legal name, postal address, privacy contact, applicable regulator details, and any required representative or data-protection officer information.</p></section>
      </article>
    </div>
    <footer><span>Listen Direct · Privacy version 1.0</span><NuxtLink to="/terms">Read Terms of Use →</NuxtLink></footer>
  </main>
</template>

<style scoped src="~/assets/legal.css"></style>
